@token={{login.response.body.accessToken}}

# Login user by email and password
# @name login
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@test.local",
  "password": "123456"
}

###

@id = {{addComment.response.body.id}}
@postId = {{addComment.response.body.postId}}
# Send comment
# @name addComment
POST http://localhost:3001/api/comments/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "postId": 10,
  "text": "Comment text for publication"
}

###
# Get comments
GET http://localhost:3001/api/comments/{{postId}}?limit=2 HTTP/1.1
Content-Type: application/json


###
# Delete comment
DELETE  http://localhost:3001/api/comments/delete/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
