@userId= {{register.response.body.id}}
@AToken={{login.response.body.accessToken}}
@RToken={{login.response.body.refreshToken}}
# Login user by email and password
# @name login
POST http://localhost:4000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@test.local",
  "password": "123456"
}

###

# Create a new user
# @name register
POST http://localhost:4000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "tet@tet.local",
  "name": "Test Doe",
  "password": "123456"
}

###


# Upload avatar
# @name uploadAvatar
POST http://localhost:4000/api/users/upload-avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{AToken}}

--boundary
Content-Disposition: form-data; name="avatar"; filename="userpic-big.jpg"
Content-Type: image/jpeg

< ../../assets/userpic-big.jpg
--boundary--

###

# Get user by ID
GET http://localhost:4000/api/users/{{userId}} HTTP/1.1
Authorization: Bearer {{AToken}}

###

# Change user password
POST http://localhost:4000/api/users/change-password HTTP/1.1
Authorization: Bearer {{AToken}}
Content-Type: application/json

{
  "currentPassword":"123456",
  "newPassword":"1234567"
}
###

# Get new JWT pair
# @name refresh
POST http://localhost:4000/api/users/refresh HTTP/1.1
Authorization: Bearer {{RToken}}

###

@postId={{createPost.response.body.id}}
@photoPostId={{uploadPhoto.response.body.id}}
# Create a new post
# @name createPost
POST http://localhost:4000/api/blog/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "type": "text",
  "title": "Long title for text publication",
  "announcement": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis erat sem, dictum ac cursus at, faucibus ut sapien. Duis ac.",
  "tags":["test", "tag2"]
}

###

# Create photo publication
# @name uploadPhoto
POST http://localhost:4000/api/blog/upload-photo/ HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{AToken}}

--boundary
Content-Disposition: form-data; name="photo"; filename="barbershop@2x.png"
Content-Type: image/png

< ../../assets/barbershop@2x.png

--boundary
Content-Disposition: form-data; name="tags"

tag,test,PhoTo
--boundary--

###

# Get publication  by ID
GET http://localhost:4000/api/blog/53 HTTP/1.1

###
# Get all posts
GET http://localhost:4000/api/blog?limit=25&page=1&tag=tag2 HTTP/1.1

###

# Get all posts by name
GET http://localhost:4000/api/blog/search?title=small%20title  HTTP/1.1

###

# Get drafts
GET http://localhost:4000/api/blog/drafts  HTTP/1.1
Authorization: Bearer {{AToken}}
Content-Type: application/json

###

# Send news
GET http://localhost:4000/api/blog/send-news HTTP/1.1
Authorization: Bearer {{AToken}}
Content-Type: application/json

###

# Repost
POST  http://localhost:4000/api/blog/repost/{{postId}} HTTP/1.1
Authorization: Bearer {{AToken}}

###

# Update post
PATCH http://localhost:4000/api/blog/update/{{postId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "title": "Small title for text publication",
  "type":"text"
}

###

# Update photo post
PATCH    http://localhost:4000/api/blog/update/{{photoPostId}}/photo HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{AToken}}

--boundary
Content-Disposition: form-data; name="photo"; filename="barbershop@2x.png"
Content-Type: image/png

< ../../assets/barbershop@2x.png

--boundary--

###
# Delete publication  by ID
DELETE http://localhost:4000/api/blog/delete/{{postId}} HTTP/1.1
Authorization: Bearer {{AToken}}

###

@commentId = {{addComment.response.body.id}}
# Send comment
# @name addComment
POST http://localhost:4000/api/comments/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

{
  "postId": 62,
  "text": "Comment text for publication"
}

###
# Get comments
GET http://localhost:4000/api/comments/{{postId}} HTTP/1.1
Content-Type: application/json

###
# Delete comment
DELETE  http://localhost:4000/api/comments/delete/{{commentId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

###

# Add/remove like
POST http://localhost:4000/api/blog/change-like-status/{{postId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{AToken}}

###
