@userId= 64e63717c3b9e4e447524178
@token={{login.response.body.accessToken}}
# Create a new user
# @name register
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "test@test.local",
  "name": "Test Doe",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}

###

# Login user by email and password
# @name login
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@test.local",
  "password": "123456"
}

###

# Change user password
POST http://localhost:3000/api/auth/change-password/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "currentPassword":"123456",
  "newPassword":"1234567"
}
###

# Get new JWT pair
POST http://localhost:3000/api/auth/refresh HTTP/1.1
Authorization: Bearer {{token}}

###
