@token={{login.response.body.accessToken}}
# Login user by email and password
# @name login
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@test.local",
  "password": "123456"
}

###

@publicationId={{createPost.response.body.id}}
# Create a new post
# @name createPost
POST http://localhost:3001/api/publication/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "text",
  "title": "Long title for text publication",
  "announcement": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis erat sem, dictum ac cursus at, faucibus ut sapien. Duis ac.",
  "tags":["test", "tag2"]
}

###

# Repost
POST  http://localhost:3001/api/publication/38/repost HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId":"2"
}

###

# Update post
PATCH http://localhost:3001/api/publication/{{publicationId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Medium title for text publication",
  "type":"text"
}

###

# Delete publication  by ID
DELETE http://localhost:3001/api/publication/{{publicationId}} HTTP/1.1
Authorization: Bearer {{token}}

###
